baseURL = 'https://www.blog.jeankaobando.com/'
languageCode = 'en-us'
title = "Blog of Jean Karlo Obando"
theme = "chringel-hugo-theme"

author = "Jean Karlo Obando"
copyright = "Copyright © 2023, Jean Karlo Obando, all rights reserved."

pluralizelisttitles = false
paginate = 10
enableEmoji = true
IsServer = true

[Params]
    name = "jeankaobando"
    description = "Personal Blog of Jean Karlo Obando"

    github_user = "boceto1"
    github_repo = "https://github.com/boceto1"
    github_banner = true

    favicon = "favicon.ico"

    # Title to be displayed in header
    headerTitle = 'blog.jeankaobando.com: ~/$'
    # User image
    titleImage = 'images/jean.jpg'
    # Copyright text displayed in footer
    footerCopyrightText = 'Jean Karlo Obando 2023'
    recentPostsOnIndex = true
    showPrevNextPostNavigation = false

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/boceto1"

[build]
  writeStats = true

[markup]
  [markup.highlight]
    style = "dracula"
